---
title: "Medidas"
author: "Efrain"
date: "2022-10-14"
output: html_document
---

```{r,message=FALSE}
library(reticulate)
library(tidyverse)
```
```{python}
import numpy as np
import pandas as pd
import random as rnd
import statistics as st
from scipy import stats
#import math as mt

iris_py = r.iris
```
# Medidas de tendencia central
```{r}
# Media
(Media <- mean(iris$Sepal.Length))
# Mediana
(Mediana <- median(iris$Sepal.Length))
# Tabla de frecuncias tranformado a dataframe
(frecuencias <- data.frame(table(iris$Sepal.Length)))
# Moda
(moda <- frecuencias[which.max(frecuencias$Freq),1])
```
```{python}
# Media
print(f"Media {st.mean(iris_py['Sepal.Length'])}")
# Mediana
print(f'Mediana {st.median(iris_py["Sepal.Length"])}')
#Moda
print(f'Moda {st.multimode(iris_py["Sepal.Length"])}')
```

# Medidas de dispercion
```{r}
# Rango
range(iris$Sepal.Length)
(rango <- range(iris$Sepal.Length)[2]-range(iris$Sepal.Length)[1])
# Varianza
(var(iris$Sepal.Length))
# Desviacion estandar
(sd(iris$Sepal.Length))
```
```{python}
# Rango
print(f'Rango {round(iris_py["Sepal.Length"].max() - iris_py["Sepal.Length"].min(),2)}')
# Varianza
print(f'Varianza {iris_py["Sepal.Length"].var()}')
# Desviacion estandar
print(f'Desviacion estandar {iris_py["Sepal.Length"].std()}')
```

# Medidas de pocision
```{r}
# Precentiles y cuantiles
(quantile(iris$Sepal.Length,0.10))
(quantile(iris$Sepal.Length,c(0.25,0.50,0.75)))
# Rango intercuartilico
IQR(iris$Sepal.Length)
# Diagrama de cajas
boxplot(iris$Sepal.Length,main="Iris boxplot",xlab="Sepal Length")
```
# Python
```{python}
# Percentiles
#Percentile 10%
print(f'Percentil 10 ={np.percentile(iris_py["Sepal.Length"],10)}')
#Percentiles 25, 50, 75
print(f'Percentiles 25,50,75,= {np.percentile(iris_py["Sepal.Length"],[25,50,75])}')
# Rango intercuartilico
print(f'Rango intercuartilico = {round(stats.iqr(iris_py["Sepal.Length"]),2)}')
```
```{r}
```


